site_name: CalTRACK Technical Documentation
theme: readthedocs
docs_dir: docs
repo_url: https://github.com/impactlab/caltrack
site_url: http://docs.caltrack.org
site_description: 'Technical Documentation for CalTRACK savings estimation procedures'

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

pages:
- Home: index.md
- Technical Specifications:
  - Data Sources: data-sources/v1.0/README.md
  - Data Preparation: data-prep/v1.0/README.md
  - Analysis of Monthly Data: savings-calculations/v1.0/monthly/README.md
  - Analysis of Daily Data: savings-calculations/v1.0/daily/README.md
  - Aggregration of Site-level Savings: aggregation/v1.0/README.md
